### PR TITLE
User page layout upgrade

### PR DESCRIPTION
**Pull request by Marco-Brescia**
This pull request includes several changes to the user interface components in the `user_profile_gui.dart` and `single_details_report.dart` files. The most important changes are the addition of a `Card` widget, updates to the input field border, and improvements to text display.

Changes to `user_profile_gui.dart`:

* Replaced `SingleChildScrollView` with a `Card` widget to enhance the visual appearance of the user profile section. [[1]](diffhunk://#diff-0530a170d0f2c7c33cbf62a9e5e1e9692bb0a8eb8f52a190fbc4fe15628b9763L97-R101) [[2]](diffhunk://#diff-0530a170d0f2c7c33cbf62a9e5e1e9692bb0a8eb8f52a190fbc4fe15628b9763R146)
* Changed the input field border from `InputBorder.none` to `UnderlineInputBorder` for better visual clarity.
* Updated the welcome text to include `municipalityName` as a fallback if `firstName` is not available.
* Adjusted the flex value of a `Text` widget to improve layout spacing.

Changes to `single_details_report.dart`:

* Added `SizedBox` widgets to improve spacing between elements in the details report.

### CODE REVIEW

**Comment by Marco-Brescia** [comment]
I’m leaving you a screenshot to help you understand the changes I made (what you see here is the edit mode of user profile).

image

**Comment by Peppe289** [comment]
> I’m leaving you a screenshot to help you understand the changes I made (what you see here is the edit mode of user profile).

LGTM! what do you think about putting the `Card` inside the `scrollview`? but that's already good!

**Review by Peppe289 — APPROVED** [review]

**Comment by Marco-Brescia** [comment]
> > I’m leaving you a screenshot to help you understand the changes I made (what you see here is the edit mode of user profile).
> 
> LGTM! what do you think about putting the `Card` inside the `scrollview`? but that's already good!

Good idea. Maybe it's better.

**Review by Luigi11162 — APPROVED** [review]
LGTM! Approved

**Review by benedettoscala — APPROVED** [review]

**Pull request merged**
