### PR TITLE
Report: add Report Details Page

### PR DESCRIPTION
**Pull request by Peppe289**
Add pages for `RF_GSA_7` and `RF_GSC_7`. There is no need for a controller or DAO because the `Report` object is passed through the widget's constructor. In this commit, we have implemented only the view.

### CODE REVIEW

**Review by Luigi11162 — APPROVED** [review]
Approved

**Review by benedettoscala — APPROVED** [review]
Looks good to me. Approved!

**Review by GiuseppeGambardella — APPROVED** [review]
Approved

**Comment by Marco-Brescia** [comment]
This requirement is similar to RF_GSA_7.

**Comment by Peppe289** [comment]
> This requirement is similar to RF_GSA_7.

I will also place this RF on the right side. Thanks!

**Review by FaiellaFrancesco — APPROVED** [review]
approved

**Review by Luigi11162 — CHANGES_REQUESTED** [review]
Resolve conflicts

**Comment by Peppe289** [comment]
As requested, I have separated the report details pages for the municipal manager and the citizen. I have also removed the changes from the homepage so that the merge can proceed without conflicts. To access the pages, make sure to include the report object when calling the constructor.

Example of activity transition:

```dart
class TestingPage extends StatefulWidget {
  const TestingPage({super.key});

  @override
  State<TestingPage> createState() => _TestingPageState();
}

class _TestingPageState extends State<TestingPage> {
  Report report = Report(
    description:
    'Description',
    photo: null,
    address: {
      'street': 'Via Benedetto',
      'number': '69',
    },
    city: 'City',
    uid: '<USER-UID>',
    title: 'Titolo super sexy',
    status: StatusReport.inProgress,
    priority: PriorityReport.high,
    reportDate: Timestamp.now(),
    authorFirstName: 'Manuel',
    authorLastName: 'Cieri',
  );

  @override
  Widget build(BuildContext context) {
    return Container(
      child: ElevatedButton(
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (context) => DettagliSegnalazioneComune(
                  report: report,
                ),
              ),
            );
          },
          child: const Text('button')),
    );
  }
}
```

**Review by Luigi11162 — APPROVED** [review]
Perfect, no conflicts. Approved

**Pull request merged**
