### PR TITLE
Test change status

### PR DESCRIPTION
**Pull request by Borax-Gargamella**
This pull request introduces several changes to the `gestione_segnalazione_comune` module to enhance the status management of reports. The changes include modifying the status transition logic, updating the controller to handle new parameters, and adding tests for the new status change rules.

### Status Management Enhancements:

* [`src/lib/gestione_segnalazione_comune/dettagli_segnalazione_comune_gui.dart`](diffhunk://#diff-e9eea0e84133c414dec1af4c2d462ef338f24b04efae4989f9b6ec46b34af302L24-R42): Updated the `_filteredStatusValues` method to return specific next statuses instead of sublists, and modified `_saveReportState` to accept the old status as a parameter. [[1]](diffhunk://#diff-e9eea0e84133c414dec1af4c2d462ef338f24b04efae4989f9b6ec46b34af302L24-R42) [[2]](diffhunk://#diff-e9eea0e84133c414dec1af4c2d462ef338f24b04efae4989f9b6ec46b34af302R115-R116) [[3]](diffhunk://#diff-e9eea0e84133c414dec1af4c2d462ef338f24b04efae4989f9b6ec46b34af302L133) [[4]](diffhunk://#diff-e9eea0e84133c414dec1af4c2d462ef338f24b04efae4989f9b6ec46b34af302L148-R155)

### Controller Updates:

* [`src/lib/gestione_segnalazione_comune/gestione_segnalazione_comune_controller.dart`](diffhunk://#diff-baca7b9053e316539b9fa57db40b4446aa7b969f5480d5c460e19d80b8c7fd83L43-R79): Refactored the `MunicipalityReportManagementController` to take DAOs as parameters and added a new constructor for testing. Introduced the `isValidStatusChange` method to validate status transitions. [[1]](diffhunk://#diff-baca7b9053e316539b9fa57db40b4446aa7b969f5480d5c460e19d80b8c7fd83L43-R79) [[2]](diffhunk://#diff-baca7b9053e316539b9fa57db40b4446aa7b969f5480d5c460e19d80b8c7fd83R106-R162)

### Testing:

* [`src/test/status_change_test.dart`](diffhunk://#diff-46e23def3936cc6c3a127f8cb123a9e6ab75457645fa899be883fada31feaa8aR1-R151): Added comprehensive tests for the status change logic, including scenarios for invalid transitions and valid transitions following the correct order.

### CODE REVIEW

**Review by FaiellaFrancesco — APPROVED** [review]
Nice job 👍

**Review by Luigi11162 — APPROVED** [review]
LGTM! Approved

**Review by benedettoscala — APPROVED** [review]

**Review by domyz21 — COMMENTED** [review]
good job pal

**Review by domyz21 — APPROVED** [review]
good job pal

**Pull request merged**
