### PR TITLE
Hotfix: fix some stuff in visualizzazione segnalazioni

### PR DESCRIPTION
**Pull request by Peppe289**
This pull request includes several changes to enhance the functionality and maintainability of the codebase in the `src/lib` directory. The most important changes involve modifying the constructors for better readability, adding a new category field to reports, and improving the layout of widgets.

### Constructor readability improvements:
* [`src/lib/gestione_admin/admin_gui.dart`](diffhunk://#diff-eaef34420165779c743026847bc1ad60b7e705d228a99d4aa01c525fb4214620L35-R36): Reformatted the constructor of `AdminHomePage` for better readability.

### Report enhancements:
* [`src/lib/gestione_segnalazione_cittadino/my_segnalazioni_gui.dart`](diffhunk://#diff-499953250f97818cffaac7a7140b91b3bf66c42d43a4a1439c4287004db8c954L151-R153): Added a `category` field to the `CardWidget` instantiation in `_MyReportsListState`.
* [`src/lib/gestione_segnalazione_cittadino/visualizzazione_segnalazioni_gui.dart`](diffhunk://#diff-520ffbfdd0d17c808c20837ddc42922f7077eeb46003a92f3449119f53be86edR361-R362): Added a `category` field to the `CardWidget` instantiation in `_ReportsListCitizenState`.
* [`src/lib/gestione_segnalazione_comune/visualizzazione_segnalazioni_comune_gui.dart`](diffhunk://#diff-5c56a00e92e01522427953a51473d61382885f7053df2b5626a4535c9914f04cL327-R329): Added a `category` field to the `CardWidget` instantiation in `_ReportsListMunicipalityState`.

### Widget layout improvements:
* [`src/lib/widgets/single_details_report.dart`](diffhunk://#diff-9bf4db7b2c7ebc31da04f26de7796b41ded75c5ec2cd8126591ed1bcfb9da108L136-R153): Changed `_statusPriority` to use `Wrap` instead of `Row` and added `IntrinsicWidth` for better layout handling. Also added a new `_categoryCard` widget to display the report category. [[1]](diffhunk://#diff-9bf4db7b2c7ebc31da04f26de7796b41ded75c5ec2cd8126591ed1bcfb9da108L136-R153) [[2]](diffhunk://#diff-9bf4db7b2c7ebc31da04f26de7796b41ded75c5ec2cd8126591ed1bcfb9da108R184-R198) [[3]](diffhunk://#diff-9bf4db7b2c7ebc31da04f26de7796b41ded75c5ec2cd8126591ed1bcfb9da108L221-R244)

### Minor changes:
* [`src/lib/gestione_segnalazione_cittadino/my_segnalazioni_gui.dart`](diffhunk://#diff-499953250f97818cffaac7a7140b91b3bf66c42d43a4a1439c4287004db8c954R3): Added a blank line for better readability.
* [`src/lib/gestione_segnalazione_comune/dettagli_segnalazione_comune_gui.dart`](diffhunk://#diff-e9eea0e84133c414dec1af4c2d462ef338f24b04efae4989f9b6ec46b34af302L63-R65): Reformatted the `onPriorityButton` method for better readability.
* [`src/lib/user_management/user_profile_gui.dart`](diffhunk://#diff-0530a170d0f2c7c33cbf62a9e5e1e9692bb0a8eb8f52a190fbc4fe15628b9763L109-R110): Reformatted the `Navigator.pushAndRemoveUntil` call for better readability.

### CODE REVIEW

**Review by benedettoscala — APPROVED** [review]

**Review by Luigi11162 — APPROVED** [review]
LGTM! Approved

**Review by Marco-Brescia — CHANGES_REQUESTED** [review]
Code LGTM, but i think layout should be better. I think that "in lavorazione" "rifiuti" and "bassa" should stay top-left. The text at the bottom should be fixed in layout, i think it's not that good. In general, not bad.

**Comment by Peppe289** [comment]
> Code LGTM, but i think layout should be better. I think that "in lavorazione" "rifiuti" and "bassa" should stay top-left. The text at the bottom should be fixed in layout, i think it's not that good. In general, not bad.

Is it sufficiently fixed this way?

Screenshot_20241214_230946

**Review by Marco-Brescia — APPROVED** [review]
Very good fix. Approved

**Review by Type-Here — APPROVED** [review]
LGTM

**Pull request merged**
